server:
  port: 5555

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
    monolito:
      path: /**
      strip-prefix: false
      
  sensitive-headers:
  - Cookie, Authorization

management:
  endpoints:
    web:
      exposure:
        include:
        - "routes"
        